import { LayoutDashboard, KanbanSquare, Database, Package, Settings, Users, BarChart3, MessageSquare, CalendarDays, PhoneCall, ClipboardList, Recycle, FileText, Tag } from 'lucide-react';
import type { MenuItem } from '../components/SidebarMenuItem';
import { MenuCategory } from '../types';

// Hierarchical sidebar configuration used by the virtualized Sidebar
export const HIERARCHICAL_MENU_CONFIG: MenuCategory[] = [
  {
    id: 'home',
    label: 'Dashboard',
    icon: LayoutDashboard,
    level: 1,
    parentId: null,
    route: 'home',
    isExpandable: false,
    children: [],
  },
  {
    id: 'sales',
    label: 'Sales',
    icon: BarChart3,
    level: 1,
    parentId: null,
    isExpandable: true,
    children: [
      {
        id: 'sales-pipeline',
        label: 'Pipeline',
        icon: KanbanSquare,
        level: 2,
        parentId: 'sales',
        isExpandable: true,
        children: [
          {
            id: 'sales-pipeline-board',
            label: 'Pipelines',
            icon: KanbanSquare,
            level: 3,
            parentId: 'sales-pipeline',
            route: 'sales-pipeline-board',
            isExpandable: false,
          },
        ],
      },
      {
        id: 'sales-database',
        label: 'Database',
        icon: Database,
        level: 2,
        parentId: 'sales',
        isExpandable: true,
        children: [
          {
            id: 'sales-database-customer-database',
            label: 'Customer Database',
            icon: Users,
            level: 3,
            parentId: 'sales-database',
            route: 'sales-database-customer-database',
            isExpandable: false,
          },
        ],
      },
      {
        id: 'sales-transactions',
        label: 'Transactions',
        icon: ClipboardList,
        level: 2,
        parentId: 'sales',
        isExpandable: true,
        children: [
          {
            id: 'sales-transaction-sales-inquiry',
            label: 'Sales Inquiry',
            icon: FileText,
            level: 3,
            parentId: 'sales-transactions',
            route: 'sales-transaction-sales-inquiry',
            isExpandable: false,
          },
          {
            id: 'sales-transaction-sales-order',
            label: 'Sales Orders',
            icon: FileText,
            level: 3,
            parentId: 'sales-transactions',
            route: 'sales-transaction-sales-order',
            isExpandable: false,
          },
          {
            id: 'sales-transaction-order-slip',
            label: 'Order Slips',
            icon: FileText,
            level: 3,
            parentId: 'sales-transactions',
            route: 'sales-transaction-order-slip',
            isExpandable: false,
          },
          {
            id: 'sales-transaction-invoice',
            label: 'Invoices',
            icon: FileText,
            level: 3,
            parentId: 'sales-transactions',
            route: 'sales-transaction-invoice',
            isExpandable: false,
          },
          {
            id: 'sales-transaction-product-promotions',
            label: 'Product Promotions',
            icon: Tag,
            level: 3,
            parentId: 'sales-transactions',
            route: 'sales-transaction-product-promotions',
            isExpandable: false,
          },
        ],
      },
      {
        id: 'sales-performance',
        label: 'Performance',
        icon: BarChart3,
        level: 2,
        parentId: 'sales',
        isExpandable: true,
        children: [
          {
            id: 'sales-performance-management-dashboard',
            label: 'Management Dashboard',
            icon: BarChart3,
            level: 3,
            parentId: 'sales-performance',
            route: 'sales-performance-management-dashboard',
            isExpandable: false,
          },
        ],
      },
    ],
  },
  {
    id: 'warehouse',
    label: 'Warehouse',
    icon: Package,
    level: 1,
    parentId: null,
    isExpandable: true,
    children: [
      {
        id: 'warehouse-inventory',
        label: 'Inventory',
        icon: Package,
        level: 2,
        parentId: 'warehouse',
        isExpandable: true,
        children: [
          {
            id: 'warehouse-inventory-product-database',
            label: 'Product Database',
            icon: Package,
            level: 3,
            parentId: 'warehouse-inventory',
            route: 'warehouse-inventory-product-database',
            isExpandable: false,
          },
          {
            id: 'warehouse-inventory-reorder-report',
            label: 'Reorder Report',
            icon: ClipboardList,
            level: 3,
            parentId: 'warehouse-inventory',
            route: 'warehouse-inventory-reorder-report',
            isExpandable: false,
          },
        ],
      },
    ],
  },
  {
    id: 'maintenance',
    label: 'Maintenance',
    icon: Settings,
    level: 1,
    parentId: null,
    isExpandable: true,
    children: [
      {
        id: 'maintenance-profile',
        label: 'Profile',
        icon: Users,
        level: 2,
        parentId: 'maintenance',
        isExpandable: true,
        children: [
          {
            id: 'maintenance-profile-staff-and-agents',
            label: 'Staff & Agents',
            icon: Users,
            level: 3,
            parentId: 'maintenance-profile',
            route: 'maintenance-profile-staff-and-agents',
            isExpandable: false,
          },
        ],
      },
      {
        id: 'maintenance-system',
        label: 'System',
        icon: Settings,
        level: 2,
        parentId: 'maintenance',
        isExpandable: true,
        children: [
          {
            id: 'maintenance-system-recycle-bin',
            label: 'Recycle Bin',
            icon: Recycle,
            level: 3,
            parentId: 'maintenance-system',
            route: 'maintenance-system-recycle-bin',
            isExpandable: false,
          },
          {
            id: 'maintenance-system-settings-permissions',
            label: 'Settings & Permissions',
            icon: Settings,
            level: 3,
            parentId: 'maintenance-system',
            route: 'maintenance-system-settings-permissions',
            isExpandable: false,
          },
        ],
      },
    ],
  },
  {
    id: 'communication',
    label: 'Communication',
    icon: MessageSquare,
    level: 1,
    parentId: null,
    isExpandable: true,
    children: [
      {
        id: 'communication-messaging',
        label: 'Messaging',
        icon: MessageSquare,
        level: 2,
        parentId: 'communication',
        isExpandable: true,
        children: [
          {
            id: 'communication-messaging-inbox',
            label: 'Inbox',
            icon: MessageSquare,
            level: 3,
            parentId: 'communication-messaging',
            route: 'communication-messaging-inbox',
            isExpandable: false,
          },
        ],
      },
      {
        id: 'communication-productivity',
        label: 'Productivity',
        icon: ClipboardList,
        level: 2,
        parentId: 'communication',
        isExpandable: true,
        children: [
          {
            id: 'communication-productivity-calendar',
            label: 'Calendar',
            icon: CalendarDays,
            level: 3,
            parentId: 'communication-productivity',
            route: 'communication-productivity-calendar',
            isExpandable: false,
          },
          {
            id: 'communication-productivity-daily-call-monitoring',
            label: 'Daily Call Monitoring',
            icon: PhoneCall,
            level: 3,
            parentId: 'communication-productivity',
            route: 'communication-productivity-daily-call-monitoring',
            isExpandable: false,
          },
          {
            id: 'communication-productivity-tasks',
            label: 'Tasks',
            icon: ClipboardList,
            level: 3,
            parentId: 'communication-productivity',
            route: 'communication-productivity-tasks',
            isExpandable: false,
          },
        ],
      },
    ],
  },
  {
    id: 'accounting',
    label: 'Accounting',
    icon: FileText,
    level: 1,
    parentId: null,
    isExpandable: true,
    children: [
      {
        id: 'accounting-reports',
        label: 'Reports',
        icon: FileText,
        level: 2,
        parentId: 'accounting',
        isExpandable: true,
        children: [
          {
            id: 'accounting-reports-overview',
            label: 'Accounting Overview',
            icon: FileText,
            level: 3,
            parentId: 'accounting-reports',
            route: 'accounting-reports-overview',
            isExpandable: false,
          },
        ],
      },
    ],
  },
];

// Flattened config for permission checks and legacy integrations
export const SIDEBAR_CONFIG: MenuItem[] = [
  { id: 'home', icon: LayoutDashboard, label: 'Dashboard', group: 'home', badge: 0 },
  { id: 'sales-pipeline-board', icon: KanbanSquare, label: 'Pipelines', group: 'sales', badge: 0 },
  { id: 'sales-database-customer-database', icon: Users, label: 'Customer Database', group: 'sales', badge: 0 },
  { id: 'warehouse-inventory-product-database', icon: Package, label: 'Product Database', group: 'warehouse', badge: 0 },
  { id: 'warehouse-inventory-reorder-report', icon: ClipboardList, label: 'Reorder Report', group: 'warehouse', badge: 0 },
  { id: 'sales-transaction-sales-inquiry', icon: FileText, label: 'Sales Inquiry', group: 'sales', badge: 0 },
  { id: 'sales-transaction-sales-order', icon: FileText, label: 'Sales Orders', group: 'sales', badge: 0 },
  { id: 'sales-transaction-order-slip', icon: FileText, label: 'Order Slips', group: 'sales', badge: 0 },
  { id: 'sales-transaction-invoice', icon: FileText, label: 'Invoices', group: 'sales', badge: 0 },
  { id: 'maintenance-profile-staff-and-agents', icon: Users, label: 'Staff & Agents', group: 'maintenance', badge: 0 },
  { id: 'sales-performance-management-dashboard', icon: BarChart3, label: 'Management Dashboard', group: 'sales', badge: 0 },
  { id: 'communication-messaging-inbox', icon: MessageSquare, label: 'Inbox', group: 'communication', badge: 0 },
  { id: 'communication-productivity-calendar', icon: CalendarDays, label: 'Calendar', group: 'communication', badge: 0 },
  { id: 'communication-productivity-daily-call-monitoring', icon: PhoneCall, label: 'Daily Call Monitoring', group: 'communication', badge: 0 },
  { id: 'communication-productivity-tasks', icon: ClipboardList, label: 'Tasks', group: 'communication', badge: 0 },
  { id: 'maintenance-system-recycle-bin', icon: Recycle, label: 'Recycle Bin', group: 'maintenance', badge: 0 },
  { id: 'maintenance-system-settings-permissions', icon: Settings, label: 'Settings & Permissions', group: 'maintenance', badge: 0 },
  { id: 'accounting-reports-overview', icon: FileText, label: 'Accounting Overview', group: 'accounting', badge: 0 },
];

